config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: 'events#index'
    resources :events do
    resources :attendees, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendee.rb
class Attendee < ApplicationRecord
    belongs_to :user
    belongs_to :event
  
    validates :user_id, presence: true
    validates :event_id, presence: true
    validates :user_id, uniqueness: { scope: :event_id, message: "has already registered for this event" }
  end
  

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true
    validates :date, presence: true
    validates :location, presence: true
    validates :description, length: { maximum: 500 }
  
    has_many :attendees, dependent: :destroy
    has_many :users, through: :attendees
  
    def upcoming?
      date > Time.now
    end
  
    def today?
      date.to_date == Date.today
    end
  
    def send_reminder
      EventMailer.event_reminder(self).deliver_now
    end
  end
  

app/models/user.rb
class User < ApplicationRecord
    # Include Devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable, :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable, :trackable
  
    # Validations
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, length: { minimum: 6 }
    validates :user_type, inclusion: { in: ['admin', 'regular'] }

    has_many :attendees
    has_many :events, through: :attendees
  
    def admin?
      self.admin
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
  
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def after_sign_in_path_for(resource)
      events_path 
    end
  
    def after_sign_out_path_for(resource_or_scope)
      root_path
    end
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:user_type])
      devise_parameter_sanitizer.permit(:account_update, keys: [:user_type])
    end
  end
  

app/controllers/attendee_controller.rb
class AttendeesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_attendee, only: [:show, :edit, :update, :destroy]
  
    def index
      @attendees = Attendee.all
    end
  
    
    def show
    end
  
 
    def edit
    end
  
    def update
      if @attendee.update(attendee_params)
        redirect_to @attendee, notice: 'Attendee was successfully updated.'
      else
        render :edit
      end
    end
  
   
    def destroy
      @attendee.destroy
      redirect_to attendees_url, notice: 'Attendee was successfully destroyed.'
    end
  
    private
  
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end
  
    def attendee_params
      params.require(:attendee).permit(:user_id, :event_id)
    end
  end
  

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_event, only: [:show, :edit, :update, :destroy]
  
    def index
      @events = Event.all
    end
  
    def show
    end
  
    def new
      @event = Event.new
    end
  
    def create
      @event = current_user.events.build(event_params)
      if @event.save
        redirect_to @event, notice: 'Event created successfully!'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @event.update(event_params)
        redirect_to @event, notice: 'Event updated successfully!'
      else
        render :edit
      end
    end
  
    def destroy
      @event.destroy
      redirect_to events_url, notice: 'Event deleted.'
    end
  
    private
  
    def set_event
      @event = Event.find(params[:id])
    end
  
    def event_params
      params.require(:event).permit(:name, :description, :date, :location)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attendees/_form.html.erb
<%= form_with(model: attendee, local: true) do |form| %>
    <div class="card">
      <div class="card-header">
        <h4><%= attendee.new_record? ? 'Register New Attendee' : 'Edit Attendee Information' %></h4>
      </div>
      <div class="card-body">
        <div class="form-group">
          <%= form.label :user_id, class: 'form-label' %>
          <%= form.collection_select :user_id, User.all, :id, :email, { prompt: 'Select User' }, { class: 'form-control' } %>
        </div>
  
        <div class="form-group">
          <%= form.label :event_id, class: 'form-label' %>
          <%= form.collection_select :event_id, Event.all, :id, :name, { prompt: 'Select Event' }, { class: 'form-control' } %>
        </div>
      </div>
      <div class="card-footer">
        <%= form.submit attendee.new_record? ? 'Create Attendee' : 'Update Attendee', class: 'btn btn-primary' %>
        <%= link_to 'Back', attendees_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  <% end %>
  

app/views/attendees/index.html.erb
<h1>Attendees</h1>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>User</th>
            <th>Event</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @attendees.each do |attendee| %>
            <tr>
              <td><%= attendee.user.email %></td>
              <td><%= attendee.event.name %></td>
              <td>
                <%= link_to 'Show', attendee_path(attendee), class: 'btn btn-primary btn-sm' %>
                <%= link_to 'Edit', edit_attendee_path(attendee), class: 'btn btn-warning btn-sm' %>
                <%= link_to 'Delete', attendee_path(attendee), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/attendees/new.html.erb
<%= render 'form', attendee: @attendee %>

app/views/attendees/show.html.erb
<h1>Attendee Details</h1>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h4>Attendee Information</h4>
        </div>
        <div class="card-body">
          <p><strong>User:</strong> <%= @attendee.user.email %></p>
          <p><strong>Event:</strong> <%= @attendee.event.name %></p>
        </div>
        <div class="card-footer">
          <%= link_to 'Edit', edit_attendee_path(@attendee), class: 'btn btn-warning' %>
          <%= link_to 'Back', attendees_path, class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="container mt-4">
  <%= form_with(model: event, local: true, class: "row g-3") do |form| %>
    <div class="col-md-6">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="col-md-6">
      <%= form.label :date %>
      <%= form.date_select :date, class: "form-control" %>
    </div>

    <div class="col-md-6">
      <%= form.label :location %>
      <%= form.text_field :location, class: "form-control" %>
    </div>

    <div class="col-12">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Edit Event</h1>

  <%= render 'form', event: @event %>

  <%= link_to 'Back to Events', events_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/events/index.html.erb
<div class="container mt-5">
  <% if current_user.admin? %>
    <h1 class="mb-4">All Events</h1>

    <%= link_to 'New Event', new_event_path, class: 'btn btn-primary mb-3' %>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Title</th>
          <th>Date</th>
          <th>Location</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.title %></td>
            <td><%= event.date %></td>
            <td><%= event.location %></td>
            <td>
              <%= link_to 'Edit', edit_event_path(event), class: 'btn btn-warning' %>
              <%= link_to 'Show', event_path(event), class: 'btn btn-info' %>
              <%= link_to 'Delete', event_path(event), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <!-- Non-admin view -->
    <h1 class="mb-4">All Events</h1>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Title</th>
          <th>Date</th>
          <th>Location</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.title %></td>
            <td><%= event.date %></td>
            <td><%= event.location %></td>
            <td>
              <%= link_to 'Register', new_event_attendee_path(event), class: 'btn btn-primary' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Create New Event</h1>

  <%= render 'form', event: @event %>

  <%= link_to 'Back to Events', events_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/events/show.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Edit Event</h1>

  <%= render 'form', event: @event %>

  <%= link_to 'Back to Events', events_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <%= link_to 'MyApp', root_path, class: 'navbar-brand' %>
      
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Profile', edit_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>  
  <body>
    <%= yield %>
  </body>
</html>